use anyhow::{Result, bail};
use async_trait::async_trait;

use super::cmd::{run_ok, run_cmd, run_interactive};
use super::{CreateOpts, ExecResult, Mount, Runtime, SandboxInfo, SandboxStatus, SnapshotInfo};

/// Lima runtime — primary on macOS (HVF-based VM).
pub struct LimaRuntime;

impl LimaRuntime {
    /// All Lima VMs managed by devbox are prefixed with "devbox-".
    fn vm_name(name: &str) -> String {
        format!("devbox-{name}")
    }

    /// Generate a Lima YAML config for creating a VM.
    fn generate_yaml(opts: &CreateOpts) -> String {
        let cpu = if opts.cpu > 0 { opts.cpu } else { 2 };
        let memory = if opts.memory.is_empty() {
            "4GiB".to_string()
        } else {
            opts.memory.clone()
        };

        let mut mounts_yaml = String::new();
        for m in &opts.mounts {
            let host = m.host_path.display();
            let target = &m.container_path;
            let writable = if m.read_only { "false" } else { "true" };
            mounts_yaml.push_str(&format!(
                "- location: \"{host}\"\n  mountPoint: \"{target}\"\n  writable: {writable}\n"
            ));
        }
        if mounts_yaml.is_empty() {
            mounts_yaml = "- location: \"~\"\n  mountPoint: \"/workspace\"\n  writable: true\n".to_string();
        }

        format!(
            r#"# Auto-generated by devbox
vmType: "vz"
rosetta:
  enabled: true
  binfmt: true
cpus: {cpu}
memory: "{memory}"
mounts:
{mounts_yaml}
ssh:
  localPort: 0
  forwardAgent: true
"#
        )
    }

    /// Parse `limactl list --json` output to extract sandbox info.
    fn parse_list_json(output: &str) -> Vec<SandboxInfo> {
        let mut infos = vec![];
        for line in output.lines() {
            let line = line.trim();
            if line.is_empty() {
                continue;
            }
            if let Ok(v) = serde_json::from_str::<serde_json::Value>(line) {
                let name = v["name"].as_str().unwrap_or("").to_string();
                if !name.starts_with("devbox-") {
                    continue;
                }
                let sandbox_name = name.strip_prefix("devbox-").unwrap_or(&name).to_string();
                let status = match v["status"].as_str().unwrap_or("") {
                    "Running" => SandboxStatus::Running,
                    "Stopped" => SandboxStatus::Stopped,
                    other => SandboxStatus::Unknown(other.to_string()),
                };
                infos.push(SandboxInfo {
                    name: sandbox_name,
                    status,
                    runtime: "lima".to_string(),
                    created_at: None,
                    ip_address: None,
                });
            }
        }
        infos
    }
}

#[async_trait]
impl Runtime for LimaRuntime {
    fn name(&self) -> &str {
        "lima"
    }

    fn is_available(&self) -> bool {
        which::which("limactl").is_ok()
    }

    fn priority(&self) -> u32 {
        20
    }

    async fn create(&self, opts: &CreateOpts) -> Result<SandboxInfo> {
        let vm = Self::vm_name(&opts.name);

        // Check if already exists
        let result = run_cmd("limactl", &["list", "--json"]).await?;
        if result.stdout.contains(&format!("\"name\":\"{}\"", vm))
            || result.stdout.contains(&format!("\"name\": \"{}\"", vm))
        {
            bail!("Lima VM '{}' already exists. Use `devbox destroy {}` first.", vm, opts.name);
        }

        // Write temporary YAML config
        let yaml = Self::generate_yaml(opts);
        let config_path = std::env::temp_dir().join(format!("{vm}.yaml"));
        std::fs::write(&config_path, &yaml)?;

        // Create the VM
        println!("Creating Lima VM '{vm}'...");
        run_ok(
            "limactl",
            &["create", "--name", &vm, &config_path.to_string_lossy()],
        )
        .await?;

        // Start the VM
        println!("Starting Lima VM '{vm}'...");
        run_ok("limactl", &["start", &vm]).await?;

        // Clean up temp config
        let _ = std::fs::remove_file(&config_path);

        Ok(SandboxInfo {
            name: opts.name.clone(),
            status: SandboxStatus::Running,
            runtime: "lima".to_string(),
            created_at: Some(chrono_now()),
            ip_address: None,
        })
    }

    async fn start(&self, name: &str) -> Result<()> {
        let vm = Self::vm_name(name);
        run_ok("limactl", &["start", &vm]).await?;
        Ok(())
    }

    async fn stop(&self, name: &str) -> Result<()> {
        let vm = Self::vm_name(name);
        run_ok("limactl", &["stop", &vm]).await?;
        Ok(())
    }

    async fn exec_cmd(
        &self,
        name: &str,
        cmd: &[&str],
        interactive: bool,
    ) -> Result<ExecResult> {
        let vm = Self::vm_name(name);
        let mut args = vec!["shell", &vm, "--"];
        args.extend_from_slice(cmd);

        if interactive {
            run_interactive("limactl", &args).await
        } else {
            run_cmd("limactl", &args).await
        }
    }

    async fn destroy(&self, name: &str) -> Result<()> {
        let vm = Self::vm_name(name);
        // Stop first if running (ignore errors)
        let _ = run_cmd("limactl", &["stop", &vm]).await;
        run_ok("limactl", &["delete", &vm, "--force"]).await?;
        Ok(())
    }

    async fn status(&self, name: &str) -> Result<SandboxStatus> {
        let vm = Self::vm_name(name);
        let result = run_cmd("limactl", &["list", "--json"]).await?;

        for line in result.stdout.lines() {
            if let Ok(v) = serde_json::from_str::<serde_json::Value>(line.trim()) {
                if v["name"].as_str() == Some(&vm) {
                    return Ok(match v["status"].as_str().unwrap_or("") {
                        "Running" => SandboxStatus::Running,
                        "Stopped" => SandboxStatus::Stopped,
                        other => SandboxStatus::Unknown(other.to_string()),
                    });
                }
            }
        }

        Ok(SandboxStatus::NotFound)
    }

    async fn list(&self) -> Result<Vec<SandboxInfo>> {
        let result = run_cmd("limactl", &["list", "--json"]).await?;
        Ok(Self::parse_list_json(&result.stdout))
    }

    async fn snapshot_create(&self, _name: &str, _snap: &str) -> Result<()> {
        todo!("Phase 6: Lima snapshot create")
    }

    async fn snapshot_restore(&self, _name: &str, _snap: &str) -> Result<()> {
        todo!("Phase 6: Lima snapshot restore")
    }

    async fn snapshot_list(&self, _name: &str) -> Result<Vec<SnapshotInfo>> {
        todo!("Phase 6: Lima snapshot list")
    }

    async fn upgrade(&self, _name: &str, _tools: &[String]) -> Result<()> {
        todo!("Phase 5: Lima upgrade")
    }
}

fn chrono_now() -> String {
    // Simple ISO 8601 timestamp without chrono dependency
    use std::time::SystemTime;
    let now = SystemTime::now()
        .duration_since(SystemTime::UNIX_EPOCH)
        .unwrap_or_default();
    format!("{}s-since-epoch", now.as_secs())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn vm_name_prefix() {
        assert_eq!(LimaRuntime::vm_name("myapp"), "devbox-myapp");
    }

    #[test]
    fn generate_yaml_defaults() {
        let opts = CreateOpts {
            name: "test".to_string(),
            mounts: vec![],
            cpu: 0,
            memory: String::new(),
            env: Default::default(),
            env_file: None,
            sets: vec![],
            tools: vec![],
            layout: "default".to_string(),
            bare: false,
            writable: false,
        };
        let yaml = LimaRuntime::generate_yaml(&opts);
        assert!(yaml.contains("cpus: 2"));
        assert!(yaml.contains("memory: \"4GiB\""));
        assert!(yaml.contains("vmType: \"vz\""));
    }

    #[test]
    fn generate_yaml_custom() {
        let opts = CreateOpts {
            name: "test".to_string(),
            mounts: vec![Mount {
                host_path: "/home/user/project".into(),
                container_path: "/workspace".to_string(),
                read_only: true,
            }],
            cpu: 4,
            memory: "8GiB".to_string(),
            env: Default::default(),
            env_file: None,
            sets: vec![],
            tools: vec![],
            layout: "default".to_string(),
            bare: false,
            writable: false,
        };
        let yaml = LimaRuntime::generate_yaml(&opts);
        assert!(yaml.contains("cpus: 4"));
        assert!(yaml.contains("memory: \"8GiB\""));
        assert!(yaml.contains("/home/user/project"));
        assert!(yaml.contains("writable: false"));
    }

    #[test]
    fn parse_list_json_filters_devbox() {
        let json = r#"{"name":"devbox-myapp","status":"Running","dir":"/home/user/.lima/devbox-myapp","arch":"aarch64"}
{"name":"default","status":"Stopped","dir":"/home/user/.lima/default","arch":"aarch64"}
{"name":"devbox-other","status":"Stopped","dir":"/home/user/.lima/devbox-other","arch":"aarch64"}"#;

        let infos = LimaRuntime::parse_list_json(json);
        assert_eq!(infos.len(), 2);
        assert_eq!(infos[0].name, "myapp");
        assert_eq!(infos[0].status, SandboxStatus::Running);
        assert_eq!(infos[1].name, "other");
        assert_eq!(infos[1].status, SandboxStatus::Stopped);
    }
}
