use std::time::{Duration, Instant};

use anyhow::{Context, Result, bail};
use async_trait::async_trait;

use super::cmd::{run_cmd, run_interactive, run_ok};
use super::{
    CreateOpts, ExecResult, MountUpdate, Runtime, SandboxInfo, SandboxStatus, SnapshotInfo,
};

/// Lima runtime — primary on macOS (HVF-based VM).
pub struct LimaRuntime;

/// NixOS Lima image version — from https://github.com/nixos-lima/nixos-lima
const NIXOS_LIMA_VERSION: &str = "v0.0.4";

/// Ubuntu version for cloud images
const UBUNTU_VERSION: &str = "24.04";

/// Lima can report `Running` while the guest is still booting or has wedged.
/// Product operations need a working control channel, not merely a VM process.
const GUEST_PROBE_TIMEOUT: Duration = Duration::from_secs(3);
const LIST_TIMEOUT: Duration = Duration::from_secs(4);
const START_COMMAND_TIMEOUT: Duration = Duration::from_secs(45);
const START_READY_TIMEOUT: Duration = Duration::from_secs(90);
const STOP_GRACE_TIMEOUT: Duration = Duration::from_secs(10);
const STOP_FORCE_TIMEOUT: Duration = Duration::from_secs(15);
const READY_POLL_INTERVAL: Duration = Duration::from_secs(1);

impl LimaRuntime {
    /// All Lima VMs managed by devbox are prefixed with "devbox-".
    fn vm_name(name: &str) -> String {
        format!("devbox-{name}")
    }

    /// Generate a Lima YAML config for creating a NixOS VM.
    fn generate_yaml(opts: &CreateOpts) -> String {
        let cpu = if opts.cpu > 0 { opts.cpu } else { 4 };
        let memory = if opts.memory.is_empty() {
            "8GiB".to_string()
        } else {
            opts.memory.clone()
        };

        let mut mounts_yaml = String::new();
        for m in &opts.mounts {
            let host = m.host_path.display();
            let target = &m.container_path;
            let writable = if m.read_only { "false" } else { "true" };
            mounts_yaml.push_str(&format!(
                "  - location: \"{host}\"\n    mountPoint: \"{target}\"\n    writable: {writable}\n    9p:\n      cache: \"mmap\"\n"
            ));
        }
        if mounts_yaml.is_empty() {
            mounts_yaml = "  - location: \"~\"\n    writable: false\n    9p:\n      cache: \"mmap\"\n  - location: \"/tmp/lima\"\n    writable: true\n    9p:\n      cache: \"mmap\"\n".to_string();
        }

        let images_yaml = if opts.image == "ubuntu" {
            let base = format!("https://cloud-images.ubuntu.com/releases/{UBUNTU_VERSION}/release");
            format!(
                r#"images:
  - location: "{base}/ubuntu-{UBUNTU_VERSION}-server-cloudimg-arm64.img"
    arch: "aarch64"
  - location: "{base}/ubuntu-{UBUNTU_VERSION}-server-cloudimg-amd64.img"
    arch: "x86_64""#
            )
        } else {
            let base = format!(
                "https://github.com/nixos-lima/nixos-lima/releases/download/{NIXOS_LIMA_VERSION}"
            );
            format!(
                r#"images:
  - location: "{base}/nixos-lima-{NIXOS_LIMA_VERSION}-aarch64.qcow2"
    arch: "aarch64"
  - location: "{base}/nixos-lima-{NIXOS_LIMA_VERSION}-x86_64.qcow2"
    arch: "x86_64""#
            )
        };

        let image_label = if opts.image == "ubuntu" {
            "Ubuntu"
        } else {
            "NixOS"
        };

        format!(
            r#"# Auto-generated by devbox — {image_label} Lima VM
vmType: "vz"
vmOpts:
  vz:
    rosetta:
      enabled: true
      binfmt: true

{images_yaml}

cpus: {cpu}
memory: "{memory}"
disk: "20GiB"

mounts:
{mounts_yaml}
ssh:
  localPort: 0
  forwardAgent: true

portForwards:
  - proto: udp
    guestPort: 68
    guestIP: 0.0.0.0
    ignore: true

containerd:
  system: false
  user: false
"#
        )
    }

    /// Parse `limactl list --json` output to extract sandbox info.
    #[allow(dead_code)]
    fn parse_list_json(output: &str) -> Vec<SandboxInfo> {
        let mut infos = vec![];
        for line in output.lines() {
            let line = line.trim();
            if line.is_empty() {
                continue;
            }
            if let Ok(v) = serde_json::from_str::<serde_json::Value>(line) {
                let name = v["name"].as_str().unwrap_or("").to_string();
                if !name.starts_with("devbox-") {
                    continue;
                }
                let sandbox_name = name.strip_prefix("devbox-").unwrap_or(&name).to_string();
                let status = match v["status"].as_str().unwrap_or("") {
                    "Running" => SandboxStatus::Running,
                    "Stopped" => SandboxStatus::Stopped,
                    other => SandboxStatus::Unknown(other.to_string()),
                };
                infos.push(SandboxInfo {
                    name: sandbox_name,
                    status,
                    runtime: "lima".to_string(),
                    created_at: None,
                    ip_address: None,
                });
            }
        }
        infos
    }

    /// Convert the process-level Lima state into the state devbox can use.
    async fn live_status(vm: &str, value: &serde_json::Value) -> SandboxStatus {
        match value["status"].as_str().unwrap_or("") {
            "Running" => {
                // `limactl list` only says that the host process is alive.
                // A no-op shell command verifies the same path used by CLI
                // exec, the web terminal, policy application, and rebuilds.
                let probe = tokio::time::timeout(
                    GUEST_PROBE_TIMEOUT,
                    run_cmd(
                        "limactl",
                        &["shell", "--workdir", "/home", vm, "--", "true"],
                    ),
                )
                .await;

                match probe {
                    Ok(Ok(result)) if result.exit_code == 0 => SandboxStatus::Running,
                    Ok(Ok(result)) => {
                        let detail = result
                            .stderr
                            .lines()
                            .find(|line| !line.trim().is_empty())
                            .unwrap_or("guest shell probe failed")
                            .trim();
                        SandboxStatus::Unreachable(detail.to_string())
                    }
                    Ok(Err(error)) => SandboxStatus::Unreachable(error.to_string()),
                    Err(_) => SandboxStatus::Unreachable(format!(
                        "guest shell did not respond within {} seconds",
                        GUEST_PROBE_TIMEOUT.as_secs()
                    )),
                }
            }
            "Stopped" => SandboxStatus::Stopped,
            other => SandboxStatus::Unknown(other.to_string()),
        }
    }

    async fn list_json() -> Result<String> {
        tokio::time::timeout(LIST_TIMEOUT, run_ok("limactl", &["list", "--json"]))
            .await
            .context("timed out while asking Lima for VM status")?
    }

    async fn wait_until_ready(&self, name: &str, started: Instant) -> Result<()> {
        let deadline = started + START_READY_TIMEOUT;
        let mut last_status = SandboxStatus::Unknown("not probed yet".to_string());

        while Instant::now() < deadline {
            last_status = match self.status(name).await {
                Ok(status) => status,
                // Lima briefly rewrites sockets while a VM starts. A single
                // failed status read is not proof that the start failed; keep
                // it as the last diagnostic and retry until the same bounded
                // readiness deadline.
                Err(error) => SandboxStatus::Unknown(format!("status probe failed: {error:#}")),
            };
            match &last_status {
                SandboxStatus::Running => return Ok(()),
                SandboxStatus::NotFound => {
                    bail!(
                        "Lima VM '{}' disappeared while starting",
                        Self::vm_name(name)
                    );
                }
                SandboxStatus::Stopped
                | SandboxStatus::Unreachable(_)
                | SandboxStatus::Unknown(_) => {
                    tokio::time::sleep(READY_POLL_INTERVAL).await;
                }
            }
        }

        bail!(
            "Lima VM '{}' did not expose a usable guest shell within {} seconds (last state: {:?}). Stop it and start it again; if the problem persists, inspect ~/.lima/{}/ha.stderr.log and ~/.lima/{}/serial*.log",
            Self::vm_name(name),
            START_READY_TIMEOUT.as_secs(),
            last_status,
            Self::vm_name(name),
            Self::vm_name(name)
        )
    }
}

#[async_trait]
impl Runtime for LimaRuntime {
    fn name(&self) -> &str {
        "lima"
    }

    fn is_available(&self) -> bool {
        which::which("limactl").is_ok()
    }

    fn priority(&self) -> u32 {
        20
    }

    async fn create(&self, opts: &CreateOpts) -> Result<SandboxInfo> {
        let vm = Self::vm_name(&opts.name);

        // Check if already exists
        let result = run_cmd("limactl", &["list", "--json"]).await?;
        if result.stdout.contains(&format!("\"name\":\"{}\"", vm))
            || result.stdout.contains(&format!("\"name\": \"{}\"", vm))
        {
            bail!(
                "Lima VM '{}' already exists. Use `devbox destroy {}` first.",
                vm,
                opts.name
            );
        }

        // Write temporary YAML config
        let yaml = Self::generate_yaml(opts);
        let config_path = std::env::temp_dir().join(format!("{vm}.yaml"));
        std::fs::write(&config_path, &yaml)?;

        // Create and start the VM (first run downloads image)
        let image_label = if opts.image == "ubuntu" {
            "Ubuntu"
        } else {
            "NixOS"
        };

        println!("Creating {image_label} VM '{vm}'...");
        println!("  (first run downloads {image_label} image, this may take a few minutes)");
        run_ok(
            "limactl",
            &[
                "create",
                "--name",
                &vm,
                "--tty=false",
                &config_path.to_string_lossy(),
            ],
        )
        .await?;

        println!("Starting {image_label} VM '{vm}'...");
        self.start(&opts.name).await?;

        // Clean up temp config
        let _ = std::fs::remove_file(&config_path);

        Ok(SandboxInfo {
            name: opts.name.clone(),
            status: SandboxStatus::Running,
            runtime: "lima".to_string(),
            created_at: Some(super::now_rfc3339()),
            ip_address: None,
        })
    }

    async fn start(&self, name: &str) -> Result<()> {
        let vm = Self::vm_name(name);
        let started = Instant::now();
        let command =
            tokio::time::timeout(START_COMMAND_TIMEOUT, run_ok("limactl", &["start", &vm])).await;

        match command {
            Ok(Ok(_)) => {}
            Ok(Err(error)) => {
                // Another caller may have won the start race. Readiness is the
                // source of truth. An unreachable guest may just be in the
                // middle of that other start, so give it the normal readiness
                // window rather than failing at the process-level state.
                match self.status(name).await? {
                    SandboxStatus::Running => return Ok(()),
                    SandboxStatus::Unreachable(_) => {}
                    _ => {
                        return Err(error)
                            .with_context(|| format!("failed to start Lima VM '{vm}'"));
                    }
                }
            }
            Err(_) => {
                // The subprocess is killed on drop. The VM may nevertheless
                // have reached readiness just before the deadline, so probe it
                // once before reporting the command timeout.
                match self.status(name).await? {
                    SandboxStatus::Running => return Ok(()),
                    SandboxStatus::Unreachable(_) => {}
                    _ => {
                        bail!(
                            "timed out after {} seconds while starting Lima VM '{vm}'",
                            START_COMMAND_TIMEOUT.as_secs()
                        );
                    }
                }
            }
        }

        self.wait_until_ready(name, started).await
    }

    async fn stop(&self, name: &str) -> Result<()> {
        let vm = Self::vm_name(name);
        match self.status(name).await {
            Ok(SandboxStatus::Stopped) => return Ok(()),
            Ok(SandboxStatus::NotFound) => bail!("Lima VM '{vm}' does not exist"),
            Ok(
                SandboxStatus::Running | SandboxStatus::Unreachable(_) | SandboxStatus::Unknown(_),
            ) => {}
            // Stop is the recovery operation for a stale runtime. If even the
            // status command is unhealthy, still attempt the bounded graceful
            // stop and force fallback instead of making recovery impossible.
            Err(error) => {
                tracing::warn!(vm = %vm, error = %error, "Lima status probe failed before stop")
            }
        }

        let graceful =
            tokio::time::timeout(STOP_GRACE_TIMEOUT, run_cmd("limactl", &["stop", &vm])).await;

        if matches!(graceful, Ok(Ok(ref result)) if result.exit_code == 0) {
            return Ok(());
        }

        tracing::warn!(
            vm = %vm,
            "graceful Lima stop failed or timed out; forcing the VM off"
        );
        let forced = tokio::time::timeout(
            STOP_FORCE_TIMEOUT,
            run_cmd("limactl", &["stop", "--force", &vm]),
        )
        .await;

        match forced {
            Ok(Ok(result)) if result.exit_code == 0 => Ok(()),
            Ok(Ok(result)) => {
                // A stop can race with an external stop. Confirm the desired
                // end state before turning a harmless non-zero exit into an
                // error, but keep the force-stop error if that probe also
                // fails.
                if matches!(self.status(name).await, Ok(SandboxStatus::Stopped)) {
                    return Ok(());
                }
                bail!(
                    "limactl stop --force {vm} failed (exit {}): {}",
                    result.exit_code,
                    result.stderr.trim()
                )
            }
            Ok(Err(error)) => Err(error).context("failed to force-stop the Lima VM"),
            Err(_) => bail!(
                "timed out after {} seconds while force-stopping Lima VM '{vm}'",
                STOP_FORCE_TIMEOUT.as_secs()
            ),
        }
    }

    async fn exec_cmd(&self, name: &str, cmd: &[&str], interactive: bool) -> Result<ExecResult> {
        let vm = Self::vm_name(name);
        // Use --workdir to avoid "cd: No such file or directory" warnings
        // from Lima trying to match the host CWD inside the VM.
        let mut args = vec!["shell", "--workdir", "/home", &vm, "--"];
        args.extend_from_slice(cmd);

        if interactive {
            run_interactive("limactl", &args).await
        } else {
            run_cmd("limactl", &args).await
        }
    }

    fn argv(&self, name: &str, cmd: &[&str], _interactive: bool) -> Vec<String> {
        // `limactl shell` is the only entry point; it allocates a tty when
        // stdin is one, which is exactly the distinction the caller controls.
        let mut argv = vec![
            "limactl".to_string(),
            "shell".to_string(),
            "--workdir".to_string(),
            "/home".to_string(),
            Self::vm_name(name),
            "--".to_string(),
        ];
        argv.extend(cmd.iter().map(|s| s.to_string()));
        argv
    }

    async fn destroy(&self, name: &str) -> Result<()> {
        let vm = Self::vm_name(name);
        // Stop first if running (ignore errors)
        let _ = self.stop(name).await;
        run_ok("limactl", &["delete", &vm, "--force"]).await?;
        Ok(())
    }

    async fn status(&self, name: &str) -> Result<SandboxStatus> {
        let vm = Self::vm_name(name);
        let output = Self::list_json().await?;

        for line in output.lines() {
            if let Ok(v) = serde_json::from_str::<serde_json::Value>(line.trim())
                && v["name"].as_str() == Some(&vm)
            {
                return Ok(Self::live_status(&vm, &v).await);
            }
        }

        Ok(SandboxStatus::NotFound)
    }

    async fn list(&self) -> Result<Vec<SandboxInfo>> {
        let result = run_cmd("limactl", &["list", "--json"]).await?;
        Ok(Self::parse_list_json(&result.stdout))
    }

    async fn snapshot_create(&self, name: &str, snap: &str) -> Result<()> {
        let vm = Self::vm_name(name);
        run_ok("limactl", &["snapshot", "save", &vm, "--tag", snap]).await?;
        Ok(())
    }

    async fn snapshot_restore(&self, name: &str, snap: &str) -> Result<()> {
        let vm = Self::vm_name(name);
        run_ok("limactl", &["snapshot", "load", &vm, "--tag", snap]).await?;
        Ok(())
    }

    async fn snapshot_list(&self, name: &str) -> Result<Vec<SnapshotInfo>> {
        let vm = Self::vm_name(name);
        let result = run_cmd("limactl", &["snapshot", "list", &vm]).await?;
        let mut snaps = vec![];
        for line in result.stdout.lines().skip(1) {
            let parts: Vec<&str> = line.split_whitespace().collect();
            if let Some(tag) = parts.first() {
                snaps.push(SnapshotInfo {
                    name: tag.to_string(),
                    created_at: parts.get(1).unwrap_or(&"").to_string(),
                });
            }
        }
        Ok(snaps)
    }

    async fn upgrade(&self, _name: &str, _tools: &[String]) -> Result<()> {
        // Upgrade is handled by the Nix layer (nixos-rebuild), not the runtime
        Ok(())
    }

    fn supports_mount_updates(&self) -> bool {
        true
    }

    async fn update_mounts(&self, name: &str, mounts: &[super::Mount]) -> Result<MountUpdate> {
        let vm = Self::vm_name(name);
        let home = dirs::home_dir().unwrap_or_default();
        let yaml_path = home.join(format!(".lima/{vm}/lima.yaml"));

        // Read and validate everything before stopping the VM. A missing or
        // malformed config is a preflight failure, not a reason to power off a
        // healthy box.
        let yaml_bytes = std::fs::read(&yaml_path).map_err(|e| {
            anyhow::anyhow!(
                "Failed to read Lima config at {}: {}",
                yaml_path.display(),
                e
            )
        })?;
        let yaml_content = std::str::from_utf8(&yaml_bytes).with_context(|| {
            format!("Lima config at {} is not valid UTF-8", yaml_path.display())
        })?;

        let mut new_mounts_yaml = String::from("mounts:\n");
        for m in mounts {
            let host = m.host_path.display();
            let target = &m.container_path;
            let writable = if m.read_only { "false" } else { "true" };
            new_mounts_yaml.push_str(&format!(
                "  - location: \"{host}\"\n    mountPoint: \"{target}\"\n    writable: {writable}\n    9p:\n      cache: \"mmap\"\n"
            ));
        }
        if mounts.is_empty() {
            new_mounts_yaml.push_str("  - location: \"~\"\n    writable: false\n    9p:\n      cache: \"mmap\"\n  - location: \"/tmp/lima\"\n    writable: true\n    9p:\n      cache: \"mmap\"\n");
        }

        // Find and replace the mounts section
        let updated = if let Some(mounts_start) = yaml_content.find("\nmounts:\n") {
            let mounts_start = mounts_start + 1; // skip the leading newline
            // Find the next top-level key (line starting with non-space, non-dash)
            let rest = &yaml_content[mounts_start..];
            let mounts_end = rest
                .lines()
                .skip(1) // skip "mounts:" line itself
                .position(|line| {
                    !line.is_empty() && !line.starts_with(' ') && !line.starts_with('-')
                })
                .map(|pos| {
                    // Calculate byte offset
                    let mut offset = 0;
                    for (i, line) in rest.lines().enumerate() {
                        if i == 0 {
                            offset += line.len() + 1;
                            continue;
                        }
                        if i - 1 == pos {
                            break;
                        }
                        offset += line.len() + 1;
                    }
                    mounts_start + offset
                })
                .unwrap_or(yaml_content.len());

            format!(
                "{}{}{}",
                &yaml_content[..mounts_start],
                new_mounts_yaml,
                &yaml_content[mounts_end..],
            )
        } else {
            // No mounts section found, append it
            format!("{}\n{}", yaml_content.trim_end(), new_mounts_yaml)
        };

        let was_running = match self.status(name).await? {
            SandboxStatus::Running => true,
            SandboxStatus::Stopped => false,
            SandboxStatus::NotFound => bail!("Lima VM '{vm}' does not exist"),
            SandboxStatus::Unreachable(detail) | SandboxStatus::Unknown(detail) => {
                bail!("cannot safely update mounts for Lima VM '{vm}': {detail}")
            }
        };

        if was_running {
            println!("Stopping VM '{vm}'...");
            self.stop(name).await?;
        }

        // Replace the config atomically. The original bytes remain our
        // rollback record until the VM has proved it can start with the new
        // mounts; `devbox use` must never leave Lima on a project that local
        // state still says it does not use.
        if let Err(write_error) = crate::sandbox::state::write_atomically(
            &yaml_path,
            updated.as_bytes(),
            "Lima mount config",
        ) {
            if was_running && let Err(start_error) = self.start(name).await {
                bail!(
                    "writing the new Lima mounts failed: {write_error:#}; the original config is intact, but restarting VM '{vm}' also failed: {start_error:#}"
                );
            }
            return Err(write_error).context("write new Lima mount config");
        }

        // `devbox use` provisions and restores policy before attaching, so it
        // needs a running guest even when the box began stopped.
        println!("Starting VM '{vm}'...");
        if let Err(start_error) = self.start(name).await {
            // `start` can fail on readiness after the VM process is already
            // alive. Force it down before changing the config underneath it.
            let stop_error = self.stop(name).await.err();
            if let Err(rollback_error) = crate::sandbox::state::write_atomically(
                &yaml_path,
                &yaml_bytes,
                "original Lima mount config",
            ) {
                bail!(
                    "Lima could not start with the new mounts: {start_error:#}; restoring the original config also failed: {rollback_error:#}. The VM may still reference the new project; inspect {} before starting it",
                    yaml_path.display()
                );
            }
            if let Some(stop_error) = stop_error {
                bail!(
                    "Lima could not start with the new mounts: {start_error:#}; the original config was restored, but force-stopping VM '{vm}' also failed: {stop_error:#}. The VM may still be using the uncommitted mounts"
                );
            }
            if was_running && let Err(restart_error) = self.start(name).await {
                bail!(
                    "Lima could not start with the new mounts: {start_error:#}; the original config was restored, but restarting VM '{vm}' on its original mounts also failed: {restart_error:#}"
                );
            }
            return Err(start_error).context(format!(
                "Lima could not start with the new mounts; the original config and prior running state of VM '{vm}' were restored"
            ));
        }

        Ok(MountUpdate::Lima {
            yaml_path,
            original: yaml_bytes,
        })
    }

    async fn rollback_mounts(&self, name: &str, update: &MountUpdate) -> Result<()> {
        let (yaml_path, original) = match update {
            MountUpdate::Lima {
                yaml_path,
                original,
            } => (yaml_path, original),
            MountUpdate::Incus { .. } => {
                bail!("received an Incus mount rollback token in the Lima runtime")
            }
        };

        // Stop first so the running guest cannot keep using the new mount set
        // after host state has refused to record it. Even if stopping fails,
        // restore the on-disk YAML so the next successful start is consistent.
        let stop_error = self.stop(name).await.err();
        crate::sandbox::state::write_atomically(yaml_path, original, "Lima mount config rollback")?;
        if let Some(stop_error) = stop_error {
            bail!(
                "the original Lima YAML was restored, but VM '{}' could not be stopped and may still be using the uncommitted mounts: {stop_error:#}. Run `devbox stop {name}` immediately",
                Self::vm_name(name)
            );
        }
        Ok(())
    }

    // Lima caching disabled — the stop/copy-disk/restart cycle adds ~1 minute
    // overhead on macOS, which isn't worth it for typical single-VM usage.
    // Caching remains active for Incus (Linux) where `incus publish` is fast.
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::runtime::Mount;

    #[test]
    fn vm_name_prefix() {
        assert_eq!(LimaRuntime::vm_name("myapp"), "devbox-myapp");
    }

    #[test]
    fn project_mount_switches_are_supported() {
        assert!(LimaRuntime.supports_mount_updates());
    }

    #[test]
    fn generate_yaml_defaults() {
        let opts = CreateOpts {
            name: "test".to_string(),
            mounts: vec![],
            cpu: 0,
            memory: String::new(),
            env: Default::default(),
            env_file: None,
            sets: vec![],
            tools: vec![],
            bare: false,
            writable: false,
            image: "nixos".to_string(),
            cached_image: None,
        };
        let yaml = LimaRuntime::generate_yaml(&opts);
        assert!(yaml.contains("cpus: 4"));
        assert!(yaml.contains("memory: \"8GiB\""));
        assert!(yaml.contains("vmType: \"vz\""));
        assert!(yaml.contains("images:"));
        assert!(yaml.contains("nixos-lima"));
    }

    #[test]
    fn generate_yaml_custom() {
        let opts = CreateOpts {
            name: "test".to_string(),
            mounts: vec![Mount {
                host_path: "/home/user/project".into(),
                container_path: "/workspace".to_string(),
                read_only: true,
            }],
            cpu: 4,
            memory: "8GiB".to_string(),
            env: Default::default(),
            env_file: None,
            sets: vec![],
            tools: vec![],
            bare: false,
            writable: false,
            image: "nixos".to_string(),
            cached_image: None,
        };
        let yaml = LimaRuntime::generate_yaml(&opts);
        assert!(yaml.contains("cpus: 4"));
        assert!(yaml.contains("memory: \"8GiB\""));
        assert!(yaml.contains("/home/user/project"));
        assert!(yaml.contains("writable: false"));
    }

    #[test]
    fn parse_list_json_filters_devbox() {
        let json = r#"{"name":"devbox-myapp","status":"Running","dir":"/home/user/.lima/devbox-myapp","arch":"aarch64"}
{"name":"default","status":"Stopped","dir":"/home/user/.lima/default","arch":"aarch64"}
{"name":"devbox-other","status":"Stopped","dir":"/home/user/.lima/devbox-other","arch":"aarch64"}"#;

        let infos = LimaRuntime::parse_list_json(json);
        assert_eq!(infos.len(), 2);
        assert_eq!(infos[0].name, "myapp");
        assert_eq!(infos[0].status, SandboxStatus::Running);
        assert_eq!(infos[1].name, "other");
        assert_eq!(infos[1].status, SandboxStatus::Stopped);
    }

    #[test]
    fn generate_yaml_ubuntu_image() {
        let opts = CreateOpts {
            name: "test".to_string(),
            mounts: vec![],
            cpu: 0,
            memory: String::new(),
            env: Default::default(),
            env_file: None,
            sets: vec![],
            tools: vec![],
            bare: false,
            writable: false,
            image: "ubuntu".to_string(),
            cached_image: None,
        };
        let yaml = LimaRuntime::generate_yaml(&opts);
        assert!(yaml.contains("ubuntu-24.04"));
        assert!(yaml.contains("cloud-images.ubuntu.com"));
        assert!(yaml.contains("arm64"));
        assert!(yaml.contains("amd64"));
        assert!(!yaml.contains("nixos-lima"));
        assert!(yaml.contains("Ubuntu Lima VM"));
    }

    #[test]
    fn generate_yaml_uses_nixos_image() {
        let opts = CreateOpts {
            name: "test".to_string(),
            mounts: vec![],
            cpu: 0,
            memory: String::new(),
            env: Default::default(),
            env_file: None,
            sets: vec![],
            tools: vec![],
            bare: false,
            writable: false,
            image: "nixos".to_string(),
            cached_image: None,
        };
        let yaml = LimaRuntime::generate_yaml(&opts);
        assert!(yaml.contains("nixos-lima"));
        assert!(yaml.contains("aarch64"));
        assert!(yaml.contains("x86_64"));
        // Should NOT contain ubuntu
        assert!(!yaml.contains("ubuntu"));
    }

    #[test]
    fn argv_targets_the_vm() {
        let argv = LimaRuntime.argv("myapp", &["zsh", "-l"], true);
        assert_eq!(
            argv,
            vec![
                "limactl",
                "shell",
                "--workdir",
                "/home",
                "devbox-myapp",
                "--",
                "zsh",
                "-l"
            ]
        );
    }
}
