// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64 && ebpf

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type DevboxConnOwner struct {
	_        structs.HostLayout
	CgroupId uint64
	Pid      uint32
	Tid      uint32
	Ppid     uint32
	Uid      uint32
	Comm     [16]int8
}

// LoadDevbox returns the embedded CollectionSpec for Devbox.
func LoadDevbox() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_DevboxBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Devbox: %w", err)
	}

	return spec, err
}

// LoadDevboxObjects loads Devbox and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*DevboxObjects
//	*DevboxPrograms
//	*DevboxMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadDevboxObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadDevbox()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// DevboxSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type DevboxSpecs struct {
	DevboxProgramSpecs
	DevboxMapSpecs
	DevboxVariableSpecs
}

// DevboxProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type DevboxProgramSpecs struct {
	HandleAccept           *ebpf.ProgramSpec `ebpf:"handle_accept"`
	HandleExec             *ebpf.ProgramSpec `ebpf:"handle_exec"`
	HandleOpenat           *ebpf.ProgramSpec `ebpf:"handle_openat"`
	HandleTcpFinishConnect *ebpf.ProgramSpec `ebpf:"handle_tcp_finish_connect"`
	HandleTcpV4Connect     *ebpf.ProgramSpec `ebpf:"handle_tcp_v4_connect"`
	HandleTcpV6Connect     *ebpf.ProgramSpec `ebpf:"handle_tcp_v6_connect"`
}

// DevboxMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type DevboxMapSpecs struct {
	Connecting    *ebpf.MapSpec `ebpf:"connecting"`
	ExecEvents    *ebpf.MapSpec `ebpf:"exec_events"`
	FileEvents    *ebpf.MapSpec `ebpf:"file_events"`
	NetEvents     *ebpf.MapSpec `ebpf:"net_events"`
	TracedCgroups *ebpf.MapSpec `ebpf:"traced_cgroups"`
}

// DevboxVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type DevboxVariableSpecs struct {
}

// DevboxObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadDevboxObjects or ebpf.CollectionSpec.LoadAndAssign.
type DevboxObjects struct {
	DevboxPrograms
	DevboxMaps
	DevboxVariables
}

func (o *DevboxObjects) Close() error {
	return _DevboxClose(
		&o.DevboxPrograms,
		&o.DevboxMaps,
	)
}

// DevboxMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadDevboxObjects or ebpf.CollectionSpec.LoadAndAssign.
type DevboxMaps struct {
	Connecting    *ebpf.Map `ebpf:"connecting"`
	ExecEvents    *ebpf.Map `ebpf:"exec_events"`
	FileEvents    *ebpf.Map `ebpf:"file_events"`
	NetEvents     *ebpf.Map `ebpf:"net_events"`
	TracedCgroups *ebpf.Map `ebpf:"traced_cgroups"`
}

func (m *DevboxMaps) Close() error {
	return _DevboxClose(
		m.Connecting,
		m.ExecEvents,
		m.FileEvents,
		m.NetEvents,
		m.TracedCgroups,
	)
}

// DevboxVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadDevboxObjects or ebpf.CollectionSpec.LoadAndAssign.
type DevboxVariables struct {
}

// DevboxPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadDevboxObjects or ebpf.CollectionSpec.LoadAndAssign.
type DevboxPrograms struct {
	HandleAccept           *ebpf.Program `ebpf:"handle_accept"`
	HandleExec             *ebpf.Program `ebpf:"handle_exec"`
	HandleOpenat           *ebpf.Program `ebpf:"handle_openat"`
	HandleTcpFinishConnect *ebpf.Program `ebpf:"handle_tcp_finish_connect"`
	HandleTcpV4Connect     *ebpf.Program `ebpf:"handle_tcp_v4_connect"`
	HandleTcpV6Connect     *ebpf.Program `ebpf:"handle_tcp_v6_connect"`
}

func (p *DevboxPrograms) Close() error {
	return _DevboxClose(
		p.HandleAccept,
		p.HandleExec,
		p.HandleOpenat,
		p.HandleTcpFinishConnect,
		p.HandleTcpV4Connect,
		p.HandleTcpV6Connect,
	)
}

func _DevboxClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed devbox_arm64_bpfel.o
var _DevboxBytes []byte
