//! FRR configuration generation (§9.2, §10.2).
//!
//! Routers get an eBGP-unnumbered fabric: each router is its own AS, peers are
//! discovered over the link-local address of each interface, and loopbacks are
//! advertised so every node is reachable by a stable address.
//!
//! Unnumbered rather than addressed BGP peering because it is what modern
//! fabrics do and because it removes the one thing that makes hand-built labs
//! fragile — a peer address that has to agree with an address plan that has to
//! agree with an interface.
//!
//! Generation is pure and golden-file tested: `render → diff → apply → verify`
//! (§10.2) needs a render step that is byte-stable.

use std::fmt::Write as _;

use super::ipam::Plan;
use super::topology::{Node, Topology};

/// Render `frr.conf` for one router.
///
/// Returns `None` for a node that does not route.
pub fn render(topology: &Topology, plan: &Plan, node: &Node) -> Option<String> {
    if !node.role.routes() {
        return None;
    }

    let asn = *plan.asns.get(&node.name)?;
    let loopback = *plan.loopbacks.get(&node.name)?;
    let mut interfaces = topology.interfaces_of(&node.name);
    interfaces.sort();
    interfaces.dedup();

    let mut conf = String::new();
    let _ = writeln!(
        conf,
        "! Generated by devbox for lab '{}'",
        topology.lab.name
    );
    let _ = writeln!(
        conf,
        "! Node {} — AS {asn}, router-id {loopback}",
        node.name
    );
    let _ = writeln!(conf, "!");
    let _ = writeln!(conf, "frr defaults datacenter");
    let _ = writeln!(conf, "hostname {}", node.name);
    let _ = writeln!(conf, "log stdout");
    let _ = writeln!(conf, "!");

    let _ = writeln!(conf, "interface lo");
    let _ = writeln!(conf, " ip address {loopback}/32");
    let _ = writeln!(conf, "!");

    for iface in &interfaces {
        let _ = writeln!(conf, "interface {iface}");
        if let Some(addr) = plan.addr_of(&node.name, iface) {
            let _ = writeln!(conf, " ip address {}", addr.cidr());
        }
        // Unnumbered peering needs the interface to accept a peer discovered
        // over its link-local address.
        let _ = writeln!(conf, " no shutdown");
        let _ = writeln!(conf, "!");
    }

    let _ = writeln!(conf, "router bgp {asn}");
    let _ = writeln!(conf, " bgp router-id {loopback}");
    // A datacenter fabric wants routes now, not after a 30-second timer.
    let _ = writeln!(conf, " no bgp ebgp-requires-policy");
    let _ = writeln!(conf, " bgp bestpath as-path multipath-relax");
    let _ = writeln!(conf, " timers bgp 3 9");

    for iface in &interfaces {
        let _ = writeln!(conf, " neighbor {iface} interface remote-as external");
    }

    let _ = writeln!(conf, " !");
    let _ = writeln!(conf, " address-family ipv4 unicast");
    let _ = writeln!(conf, "  network {loopback}/32");
    for addr in plan.addrs_of(&node.name) {
        let _ = writeln!(conf, "  network {}", subnet_of(addr));
    }
    for iface in &interfaces {
        let _ = writeln!(conf, "  neighbor {iface} activate");
    }
    // ECMP across every spine, which is the whole point of a Clos fabric.
    let _ = writeln!(conf, "  maximum-paths 8");
    let _ = writeln!(conf, " exit-address-family");
    let _ = writeln!(conf, "!");

    Some(conf)
}

/// The subnet an interface address belongs to, in CIDR form.
fn subnet_of(addr: &super::ipam::InterfaceAddr) -> String {
    let bits = u32::from(addr.addr);
    let mask = if addr.prefix_len == 0 {
        0
    } else {
        u32::MAX << (32 - addr.prefix_len)
    };
    format!(
        "{}/{}",
        std::net::Ipv4Addr::from(bits & mask),
        addr.prefix_len
    )
}

/// Render every router's config.
pub fn render_all(topology: &Topology, plan: &Plan) -> Vec<(String, String)> {
    topology
        .nodes
        .iter()
        .filter_map(|node| render(topology, plan, node).map(|conf| (node.name.clone(), conf)))
        .collect()
}

/// The `daemons` file FRR reads to decide what to start.
///
/// Only bgpd: a lab that starts every routing daemon spends its memory on
/// protocols nobody asked for, and makes `show running-config` unreadable.
pub fn daemons() -> &'static str {
    "zebra=yes\nbgpd=yes\nospfd=no\nospf6d=no\nripd=no\nripngd=no\nisisd=no\n\
     pimd=no\nldpd=no\nnhrpd=no\neigrpd=no\nbabeld=no\nsharpd=no\npbrd=no\n\
     bfdd=no\nfabricd=no\nvrrpd=no\n"
}

/// The command that checks whether BGP has converged on a node.
pub fn convergence_check(lab: &str, node: &str) -> Vec<String> {
    // `-N <pathspace>`, matching what `start_commands` gave the daemons.
    // Without it vtysh searches the default socket directory and either finds
    // nothing or answers about an unrelated router — so a converged fabric
    // reads as failed, or an unconverged one reads as fine.
    let ns = super::wiring::netns(lab, node);
    super::wiring::in_node(
        lab,
        node,
        &["vtysh", "-N", &ns, "-c", "show bgp summary json"],
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::lab::ipam;
    use crate::lab::topology::{LabSection, Link, Role, Services};

    fn clos() -> Topology {
        Topology {
            lab: LabSection {
                name: "clos-3node".into(),
                substrate: "auto".into(),
                base: "10.0.0.0/16".into(),
                asn_base: 65000,
            },
            nodes: vec![
                Node {
                    name: "leaf1".into(),
                    role: Role::FrrRouter,
                    sets: vec![],
                    asn: None,
                },
                Node {
                    name: "leaf2".into(),
                    role: Role::FrrRouter,
                    sets: vec![],
                    asn: None,
                },
                Node {
                    name: "spine1".into(),
                    role: Role::FrrRouter,
                    sets: vec![],
                    asn: None,
                },
                Node {
                    name: "host1".into(),
                    role: Role::Host,
                    sets: vec![],
                    asn: None,
                },
            ],
            links: vec![
                Link {
                    endpoints: vec!["leaf1:eth1".into(), "spine1:eth1".into()],
                    subnet: None,
                },
                Link {
                    endpoints: vec!["leaf2:eth1".into(), "spine1:eth2".into()],
                    subnet: None,
                },
                Link {
                    endpoints: vec!["leaf1:eth2".into(), "host1:eth1".into()],
                    subnet: None,
                },
            ],
            services: Services::default(),
        }
    }

    fn config_for(name: &str) -> String {
        let t = clos();
        let plan = ipam::allocate(&t).unwrap();
        let node = t.node(name).unwrap().clone();
        render(&t, &plan, &node).expect("a router config")
    }

    #[test]
    fn a_host_gets_no_routing_config() {
        let t = clos();
        let plan = ipam::allocate(&t).unwrap();
        let host = t.node("host1").unwrap().clone();
        assert!(render(&t, &plan, &host).is_none());
    }

    #[test]
    fn a_router_config_has_its_own_asn_and_router_id() {
        let conf = config_for("leaf1");
        assert!(conf.contains("router bgp 65000"), "{conf}");
        assert!(conf.contains("bgp router-id 10."), "{conf}");
        assert!(conf.contains("hostname leaf1"));

        // Each router is its own AS — eBGP, not iBGP.
        let spine = config_for("spine1");
        assert!(spine.contains("router bgp 65002"), "{spine}");
    }

    #[test]
    fn peering_is_unnumbered_over_every_link_interface() {
        // Unnumbered removes the peer address that has to agree with the
        // address plan that has to agree with the interface.
        let conf = config_for("spine1");
        assert!(conf.contains("neighbor eth1 interface remote-as external"));
        assert!(conf.contains("neighbor eth2 interface remote-as external"));
        assert!(conf.contains("neighbor eth1 activate"));
        assert!(!conf.contains("neighbor 10."), "no addressed peers: {conf}");
    }

    #[test]
    fn loopbacks_are_advertised_so_every_node_has_a_stable_address() {
        let conf = config_for("leaf1");
        assert!(conf.contains("interface lo"));
        assert!(conf.contains("/32"), "the loopback is a host route");
        let network_lines = conf.matches("  network ").count();
        assert!(
            network_lines >= 2,
            "the loopback and each link subnet: {conf}"
        );
    }

    #[test]
    fn ecmp_is_enabled_which_is_the_point_of_a_clos_fabric() {
        let conf = config_for("leaf1");
        assert!(conf.contains("maximum-paths 8"));
        assert!(conf.contains("bestpath as-path multipath-relax"));
    }

    #[test]
    fn timers_are_short_enough_for_a_lab_to_converge_while_you_watch() {
        let conf = config_for("leaf1");
        assert!(
            conf.contains("timers bgp 3 9"),
            "a 30-second default makes a lab feel broken: {conf}"
        );
    }

    #[test]
    fn policy_is_not_required_so_routes_actually_appear() {
        // Modern FRR refuses to advertise anything over eBGP without an
        // explicit policy; in a lab that reads as "BGP is up but broken".
        let conf = config_for("leaf1");
        assert!(conf.contains("no bgp ebgp-requires-policy"));
    }

    #[test]
    fn generation_is_byte_stable() {
        // `render → diff → apply → verify` needs a render that does not churn.
        assert_eq!(config_for("leaf1"), config_for("leaf1"));

        let t = clos();
        let plan = ipam::allocate(&t).unwrap();
        assert_eq!(render_all(&t, &plan), render_all(&t, &plan));
    }

    #[test]
    fn render_all_covers_routers_only() {
        let t = clos();
        let plan = ipam::allocate(&t).unwrap();
        let configs = render_all(&t, &plan);

        assert_eq!(configs.len(), 3, "three routers, one host");
        assert!(configs.iter().all(|(name, _)| name != "host1"));
    }

    #[test]
    fn only_bgpd_is_started() {
        let d = daemons();
        assert!(d.contains("bgpd=yes"));
        assert!(d.contains("zebra=yes"));
        // Everything else off: a lab that starts every daemon spends memory on
        // protocols nobody asked for.
        assert!(d.contains("ospfd=no"));
        assert!(d.contains("isisd=no"));
        assert!(!d.contains("=yes\nospfd=yes"));
    }

    #[test]
    fn subnet_of_masks_the_host_bits() {
        let t = clos();
        let plan = ipam::allocate(&t).unwrap();
        let addr = plan.addr_of("leaf1", "eth1").unwrap();
        let subnet = subnet_of(addr);

        assert!(subnet.ends_with("/31"));
        // The subnet is the link's network address, not the interface address.
        assert_eq!(subnet, plan.links[0].subnet);
    }

    #[test]
    fn the_convergence_check_asks_for_json() {
        let cmd = crate::lab::wiring::render(&convergence_check("clos", "leaf1"));
        assert!(cmd.contains("devbox-clos-leaf1"));
        assert!(
            cmd.contains("show bgp summary json"),
            "parseable, not scraped"
        );
    }
}

/// Commands that start the routing daemons inside a router's namespace.
///
/// `zebra` then `bgpd`: zebra owns the kernel routing table and bgpd talks to
/// it over zserv, so starting bgpd first gives a daemon with nowhere to
/// install the routes it learns.
///
/// Run with `ip netns exec` because a namespace has no init — there is no
/// service manager inside one to hand this to, which is exactly the assumption
/// that left `lab up` reporting success with BGP never started.
pub fn start_commands(lab: &str, node: &str) -> Vec<Vec<String>> {
    // The namespace wiring created, not the bare node name. `ip netns exec
    // leaf1` fails with "namespace not found" and aborts before zebra starts —
    // which is every routed lab.
    let ns = super::wiring::netns(lab, node);
    let dir = format!("/etc/devbox/lab/{lab}/{node}");
    let run = format!("/run/devbox/lab/{lab}/{node}");

    let daemon = |name: &str, extra: &[&str]| -> Vec<String> {
        let mut argv = vec![
            "sudo".to_string(),
            "ip".to_string(),
            "netns".to_string(),
            "exec".to_string(),
            ns.clone(),
            name.to_string(),
            "-d".to_string(),
            "-f".to_string(),
            format!("{dir}/frr.conf"),
            "-i".to_string(),
            format!("{run}/{name}.pid"),
            // Per-namespace socket directory: every namespace runs its own
            // zebra, and a shared /var/run path would have them all talking to
            // whichever started first.
            "-z".to_string(),
            format!("{run}/zserv.api"),
            // Its own VTY pathspace: `vtysh` finds a daemon by its socket
            // directory, so without this every router's vtysh would reach
            // whichever zebra registered first.
            "-N".to_string(),
            ns.clone(),
        ];
        argv.extend(extra.iter().map(|s| s.to_string()));
        argv
    };

    vec![
        vec![
            "sudo".to_string(),
            "mkdir".to_string(),
            "-p".to_string(),
            run.clone(),
        ],
        daemon("zebra", &[]),
        daemon("bgpd", &[]),
    ]
}

#[cfg(test)]
mod start_tests {
    use super::*;

    #[test]
    fn zebra_starts_before_bgpd_in_its_own_namespace() {
        let commands = start_commands("clos", "leaf1");
        let flat: Vec<String> = commands.iter().map(|c| c.join(" ")).collect();

        let zebra = flat.iter().position(|c| c.contains("zebra")).unwrap();
        let bgpd = flat.iter().position(|c| c.contains("bgpd")).unwrap();
        assert!(
            zebra < bgpd,
            "bgpd has nowhere to install routes without zebra"
        );

        // The namespace name wiring generates, not the bare node name.
        let ns = crate::lab::wiring::netns("clos", "leaf1");
        assert!(
            flat.iter()
                .all(|c| !c.contains("zebra") || c.contains(&format!("ip netns exec {ns}"))),
            "FRR must run in the namespace that exists: {flat:?}"
        );
        assert!(
            flat.iter().any(|c| c.contains(&format!("-N {ns}"))),
            "each router needs its own VTY pathspace: {flat:?}"
        );
        // Per-namespace sockets and pidfiles, or every router talks to the
        // first zebra that started.
        assert!(
            flat.iter()
                .any(|c| c.contains("/run/devbox/lab/clos/leaf1/zserv.api"))
        );
        assert!(
            flat.iter()
                .any(|c| c.contains("mkdir -p /run/devbox/lab/clos/leaf1"))
        );
    }
}
