# Auto-generated by devbox — ai-code set
# Some AI tools may not be in nixpkgs yet; filter gracefully.
{ pkgs }:
let
  wanted = [
    "claude-code"
    "codex"
    "opencode"
    "aider-chat"
    "aichat"
  ];
  tryPkg = name:
    let val = builtins.tryEval (pkgs.${name});
    in if val.success then [ val.value ] else [];
in builtins.concatMap tryPkg wanted
