# Auto-generated by devbox — ai-code set
# Some AI tools may not be in nixpkgs; filter gracefully.
# Uses tryEval with meta.license check to handle both missing and unfree packages.
{ pkgs }:
let
  wanted = [
    "claude-code"
    "codex"
    "opencode"
    "aider-chat"
    "aichat"
  ];
  tryPkg = name:
    let
      hasPkg = builtins.hasAttr name pkgs;
      pkg = pkgs.${name};
      # Force evaluation of the package name (triggers unfree check)
      eval = builtins.tryEval (builtins.seq pkg.name pkg);
    in if hasPkg && eval.success then [ eval.value ] else [];
in builtins.concatMap tryPkg wanted
