# Auto-generated by devbox — ai-infra set
# Some AI tools may not be in nixpkgs; filter gracefully.
{ pkgs }:
let
  tryPkg = pkg:
    let eval = builtins.tryEval (builtins.seq pkg.name pkg);
    in if eval.success then [ eval.value ] else [];
  tryAttr = name:
    let eval = builtins.tryEval pkgs.${name};
    in if eval.success then tryPkg eval.value else [];
in builtins.concatLists [
  (tryAttr "ollama")
  (tryAttr "open-webui")
  (tryAttr "litellm")
  (tryAttr "mcp-hub")
  (let eval = builtins.tryEval pkgs.python312Packages.huggingface-hub;
   in if eval.success then tryPkg eval.value else [])
]
