# Auto-generated by devbox — ai-infra set
# Some AI tools may not be in nixpkgs yet; filter gracefully.
{ pkgs }:
let
  tryPkg = p:
    let val = builtins.tryEval p;
    in if val.success then [ val.value ] else [];
in builtins.concatLists [
  (tryPkg pkgs.ollama)
  (tryPkg pkgs.open-webui)
  (tryPkg pkgs.litellm)
  (tryPkg pkgs.mcp-hub)
  (tryPkg pkgs.python312Packages.huggingface-hub)
]
