use std::collections::HashMap;

/// A Nix set with its package list mapped to nixpkgs attribute paths.
#[derive(Debug, Clone)]
pub struct NixSet {
    pub name: &'static str,
    pub packages: &'static [&'static str],
}

/// All Nix sets with their nixpkgs attribute paths.
pub static NIX_SETS: &[NixSet] = &[
    NixSet {
        name: "system",
        packages: &[
            "coreutils",
            "gnugrep",
            "gnused",
            "gawk",
            "findutils",
            "diffutils",
            "gzip",
            "gnutar",
            "xz",
            "bzip2",
            "file",
            "which",
            "tree",
            "less",
            "curl",
            "wget",
            "openssh",
            "openssl",
            "cacert",
            "gnupg",
            "gcc",
            "gnumake",
            "pkg-config",
            "man-db",
        ],
    },
    NixSet {
        name: "shell",
        packages: &[
            "zellij",
            "zsh",
            "zsh-autosuggestions",
            "zsh-syntax-highlighting",
            "starship",
            "fzf",
            "zoxide",
            "direnv",
            "nix-direnv",
            "yazi",
            "micro",
        ],
    },
    NixSet {
        name: "tools",
        packages: &[
            "ripgrep",
            "fd",
            "bat",
            "eza",
            "delta",
            "sd",
            "choose",
            "jq",
            "yq-go",
            "fx",
            "htop",
            "bottom",
            "procs",
            "dust",
            "duf",
            "tokei",
            "hyperfine",
            "tealdeer",
            "httpie",
            "dog",
            "glow",
            "entr",
        ],
    },
    NixSet {
        name: "editor",
        packages: &["neovim", "helix", "nano"],
    },
    NixSet {
        name: "git",
        packages: &["git", "lazygit", "gh", "git-lfs", "git-crypt", "pre-commit"],
    },
    NixSet {
        name: "container",
        packages: &[
            "docker",
            "docker-compose",
            "lazydocker",
            "dive",
            "buildkit",
            "skopeo",
        ],
    },
    NixSet {
        name: "network",
        packages: &[
            "tailscale",
            "mosh",
            "nmap",
            "tcpdump",
            "bandwhich",
            "trippy",
            "doggo",
        ],
    },
    NixSet {
        name: "ai-code",
        packages: &["claude-code", "codex", "opencode", "aider-chat", "aichat"],
    },
    NixSet {
        name: "ai-infra",
        packages: &[
            "ollama",
            "open-webui",
            "litellm",
            "mcp-hub",
            "python312Packages.huggingface-hub",
        ],
    },
    NixSet {
        name: "lang-go",
        packages: &["go", "gopls", "golangci-lint", "delve", "gotools", "gore"],
    },
    NixSet {
        name: "lang-rust",
        packages: &[
            "rustup",
            "rust-analyzer",
            "cargo-watch",
            "cargo-edit",
            "cargo-expand",
            "sccache",
        ],
    },
    NixSet {
        name: "lang-python",
        packages: &[
            "python312",
            "uv",
            "ruff",
            "pyright",
            "python312Packages.ipython",
            "python312Packages.pytest",
        ],
    },
    NixSet {
        name: "lang-node",
        packages: &[
            "nodejs_22",
            "bun",
            "pnpm",
            "typescript",
            "nodePackages.typescript-language-server",
            "biome",
        ],
    },
    NixSet {
        name: "lang-java",
        packages: &["jdk21", "gradle", "maven", "jdt-language-server"],
    },
    NixSet {
        name: "lang-ruby",
        packages: &["ruby_3_3", "bundler", "solargraph", "rubocop"],
    },
];

/// Lookup a NixSet by name.
#[allow(dead_code)]
pub fn find_set(name: &str) -> Option<&'static NixSet> {
    NIX_SETS.iter().find(|s| s.name == name)
}

/// Generate a Nix expression file for a single set.
/// Returns: `{ pkgs }: with pkgs; [ pkg1 pkg2 ... ]`
pub fn generate_set_nix(set: &NixSet) -> String {
    let mut nix = format!("# Auto-generated by devbox — {} set\n", set.name);
    nix.push_str("{ pkgs }:\nwith pkgs;\n[\n");
    for pkg in set.packages {
        nix.push_str(&format!("  {pkg}\n"));
    }
    nix.push_str("]\n");
    nix
}

/// Generate the /etc/devbox/sets/default.nix that imports all sets.
pub fn generate_sets_default_nix() -> String {
    let mut nix = String::from("# Auto-generated by devbox — set index\n{ pkgs }:\n{\n");
    for set in NIX_SETS {
        nix.push_str(&format!(
            "  {} = import ./{}.nix {{ inherit pkgs; }};\n",
            set.name.replace('-', "_"),
            set.name
        ));
    }
    nix.push_str("}\n");
    nix
}

/// Generate a devbox-state.toml from active sets and languages.
pub fn generate_state_toml(
    sets: &HashMap<String, bool>,
    languages: &HashMap<String, bool>,
    custom_packages: &HashMap<String, String>,
) -> String {
    let mut toml = String::from("[sets]\n");
    let set_names = [
        "system",
        "shell",
        "tools",
        "editor",
        "git",
        "container",
        "network",
        "ai_code",
        "ai_infra",
    ];
    for name in &set_names {
        let enabled = sets.get(*name).copied().unwrap_or(false);
        toml.push_str(&format!("{name} = {enabled}\n"));
    }

    toml.push_str("\n[languages]\n");
    let lang_names = ["go", "rust", "python", "node", "java", "ruby"];
    for name in &lang_names {
        let enabled = languages.get(*name).copied().unwrap_or(false);
        toml.push_str(&format!("{name} = {enabled}\n"));
    }

    if !custom_packages.is_empty() {
        toml.push_str("\n[custom_packages]\n");
        for (name, ref_str) in custom_packages {
            toml.push_str(&format!("{name} = \"{ref_str}\"\n"));
        }
    }

    toml
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn all_sets_present() {
        assert_eq!(NIX_SETS.len(), 15);
        assert!(find_set("system").is_some());
        assert!(find_set("lang-go").is_some());
        assert!(find_set("nonexistent").is_none());
    }

    #[test]
    fn generate_set_nix_output() {
        let set = find_set("editor").unwrap();
        let nix = generate_set_nix(set);
        assert!(nix.contains("{ pkgs }:"));
        assert!(nix.contains("neovim"));
        assert!(nix.contains("helix"));
    }

    #[test]
    fn generate_default_nix_output() {
        let nix = generate_sets_default_nix();
        assert!(nix.contains("system = import ./system.nix"));
        assert!(nix.contains("lang_go = import ./lang-go.nix"));
    }

    #[test]
    fn generate_state_toml_output() {
        let mut sets = HashMap::new();
        sets.insert("system".to_string(), true);
        sets.insert("ai_code".to_string(), true);
        let mut langs = HashMap::new();
        langs.insert("go".to_string(), true);
        let toml = generate_state_toml(&sets, &langs, &HashMap::new());
        assert!(toml.contains("system = true"));
        assert!(toml.contains("ai_code = true"));
        assert!(toml.contains("go = true"));
        assert!(toml.contains("network = false"));
    }
}
